# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ....core.datetime_utils import serialize_datetime


class LicenseStatsResponse(pydantic.BaseModel):
    license_days_granted: typing.Optional[float] = pydantic.Field(
        alias="licenseDaysGranted", description=("Total number of license days granted\n")
    )
    license_days_used: typing.Optional[float] = pydantic.Field(
        alias="licenseDaysUsed", description=("Number of license days used\n")
    )
    license_days_remaining: typing.Optional[float] = pydantic.Field(
        alias="licenseDaysRemaining", description=("Number of license days remaining\n")
    )
    active_licenses: typing.Optional[float] = pydantic.Field(
        alias="activeLicenses", description=("Number of active/valid licenses\n")
    )

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        allow_population_by_field_name = True
        json_encoders = {dt.datetime: serialize_datetime}
